version: "3.7"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5417:5432"
    environment:
      POSTGRES_DB: ds_airflow
      POSTGRES_USER: ds_airflow
      POSTGRES_PASSWORD: insecure

  dso_database:
    image: amsterdam/postgres11
    ports:
      - "5416:5432"
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: dataservices
      POSTGRES_PASSWORD: insecure
    extra_hosts:
      admin.data.amsterdam.nl: 10.243.16.4

  airflow:
    build: src
    container_name: airflow
    environment:
      AIRFLOW_CONN_POSTGRES_DEFAULT:
        "postgresql://dataservices:insecure@dso_database:5432\
        /dataservices?cursor=dictcursor&"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql://ds_airflow:insecure@database:5432/ds_airflow"
      AIRFLOW_CONN_ORACLE_DWH_STADSDELEN:
        "oracle://oracle_user:insecure@localhost:1521/SID001?encoding=UTF-8&nencoding=UTF-8"
      AIRFLOW_CONN_OBJECTSTORE_DATASERVICES: "s3://dataservices:${DATASERVICES_PASSWD}@\
        356c76835e424b968ed6d654c51204f0"
      AIRFLOW_CONN_OBJECTSTORE_PARKEERVAKKEN: "s3://parkeervakken:${PARKEERVAKKEN_PASSWD}@\
        091e3bedc85447ef936e82bcda88fcac"
      AIRFLOW_CONN_SWIFT_DEFAULT: "s3://vsd_user:${VSD_PASSWD}@\
        4028c44d91dc48b8990069433c203c1f"
      FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080/
      DATAPUNT_ENVIRONMENT: development
      SLACK_WEBHOOK_HOST: https://hooks.slack.com/services
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      OS_USERNAME: vsd_user
      OS_PASSWORD: ${VSD_PASSWD}
      OS_TENANT_NAME: 4028c44d91dc48b8990069433c203c1f
      OS_AUTH_URL: https://identity.stack.cloudvps.com/v2.0
      DAG_SYNC_PATH: /tmp/synced-dags
      OPENBARE_VERLICHTING_DATA_SRC: https://asd2.techtek.eu/asd/services/rest_sia.php/SIAService/objecten
      OPENBARE_VERLICHTING_DATA_TYPES_SRC: https://asd2.techtek.eu/asd/services/rest_sia.php/SIAService/types
    volumes:
      - ./src/dags:/usr/local/airflow/dags
      - ./src/plugins:/usr/local/airflow/plugins
      - ./src/vars:/usr/local/airflow/vars
      - ./src/vsd:/usr/local/airflow/vsd
      - ./develop:/usr/local/airflow/develop
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "8080:8080"
    # command: sleep infinity
