version: "3.7"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5416:5432"
    environment:
      POSTGRES_DB: ds_airflow
      POSTGRES_USER: ds_airflow
      POSTGRES_PASSWORD: insecure

  airflow:
    build: src
    container_name: airflow
    environment:
      POSTGRES_HOST: "database"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ds_airflow
      POSTGRES_USER: ds_airflow
      POSTGRES_PASSWORD: insecure
      AIRFLOW_CONN_POSTGRES_DEFAULT: |
        postgresql://ds_airflow:insecure@database:5432/ds_airflow?cursor=dictcursor&
      FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080/
      DATAPUNT_ENVIRONMENT: development
      SLACK_WEBHOOK_HOST: https://hooks.slack.com/services
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
      OS_USERNAME: vsd_user
      OS_PASSWORD: ${VSD_PASSWD}
      OS_TENANT_NAME: 4028c44d91dc48b8990069433c203c1f
      OS_AUTH_URL: https://identity.stack.cloudvps.com/v2.0
      DAG_SYNC_PATH: /tmp/synced-dags
      PARKEERVAKKEN: ${PARKEERVAKKEN}
    volumes:
      - ./src/dags:/usr/local/airflow/dags
      - ./src/plugins:/usr/local/airflow/plugins
      - ./src/vars:/usr/local/airflow/vars
      - ./develop:/usr/local/airflow/develop
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp:/tmp/


    ports:
      - "8080:8080"
    
    # command: sleep infinity
