--
-- PostgreSQL database dump
--
-- Colors were originally generated by the assign_colors.py script. Then saved in this file
-- with a pg_dump for CREATE TABLE parkeerzones_map_color AS SELECT ogc_fid, gebied_code, color from parkeerzones
-- to keep colors consistent for multiple imports
-- If data is changed colors can be tweaked manually , or assign_colors.py  does run only for parkeerzones
-- that are new and do not yet have a color assigned.
--

CREATE TABLE public.parkeerzones_map_color (
    ogc_fid integer,
    gebied_code character varying(10),
    color character varying(7)
);

INSERT INTO public.parkeerzones_map_color VALUES (11, 'ZB65X', NULL);
INSERT INTO public.parkeerzones_map_color VALUES (35, 'OS76X', NULL);
INSERT INTO public.parkeerzones_map_color VALUES (31, 'ZB69G', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (45, 'WM58X', NULL);
INSERT INTO public.parkeerzones_map_color VALUES (86, 'BV85', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (38, 'ZB66A', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (85, 'ZB07', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (105, 'BV86', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (100, 'ZB10', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (81, 'BL02', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (60, 'ZO03A', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (94, 'ZO03A', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (70, 'ZB67B', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (34, 'OS76', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (79, 'AN05A', '#BED200');
INSERT INTO public.parkeerzones_map_color VALUES (95, 'ZO70', NULL);
INSERT INTO public.parkeerzones_map_color VALUES (113, 'AN95X', NULL);
INSERT INTO public.parkeerzones_map_color VALUES (101, 'SV52', NULL);
INSERT INTO public.parkeerzones_map_color VALUES (115, 'ZB08X', NULL);
INSERT INTO public.parkeerzones_map_color VALUES (4, 'ZB66A', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (111, 'AN07', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (5, 'BL03', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (58, 'WP60D', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (59, 'WP60A', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (47, 'WH82X', NULL);
INSERT INTO public.parkeerzones_map_color VALUES (66, 'GV81X', NULL);
INSERT INTO public.parkeerzones_map_color VALUES (48, 'SO37', NULL);
INSERT INTO public.parkeerzones_map_color VALUES (112, 'AN09A', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (40, 'WP62', '#BED200');
INSERT INTO public.parkeerzones_map_color VALUES (39, 'WP60E', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (56, 'WP60C', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (61, 'WP60B', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (46, 'WH82', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (44, 'WP61H', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (43, 'WH84H', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (65, 'ZB66B', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (64, 'ZB67A', '#00A03C');
INSERT INTO public.parkeerzones_map_color VALUES (28, 'ZO03B', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (57, 'SO35B', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (96, 'AN08A', '#767676');
INSERT INTO public.parkeerzones_map_color VALUES (114, 'ZB08', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (37, 'SO36', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (14, 'WM59B', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (15, 'WM59A', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (29, 'ZO04', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (62, 'ZB67C', '#767676');
INSERT INTO public.parkeerzones_map_color VALUES (63, 'WP63', '#BED200');
INSERT INTO public.parkeerzones_map_color VALUES (36, 'WP61C', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (109, 'AN06', '#767676');
INSERT INTO public.parkeerzones_map_color VALUES (91, 'BA01C', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (90, 'BA01A', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (92, 'BA01B', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (93, 'ZO01', '#767676');
INSERT INTO public.parkeerzones_map_color VALUES (97, 'AN09A', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (98, 'AN09B', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (110, 'AN09A', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (10, 'WH98', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (84, 'ZD03B', '#BED200');
INSERT INTO public.parkeerzones_map_color VALUES (76, 'ZD03A', '#BED200');
INSERT INTO public.parkeerzones_map_color VALUES (89, 'BV87', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (8, 'ZD04D', '#00A03C');
INSERT INTO public.parkeerzones_map_color VALUES (7, 'ZD04C', '#00A03C');
INSERT INTO public.parkeerzones_map_color VALUES (49, 'ZD04A', '#00A03C');
INSERT INTO public.parkeerzones_map_color VALUES (78, 'ZD04B', '#00A03C');
INSERT INTO public.parkeerzones_map_color VALUES (107, 'WM55', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (32, 'WM55C', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (108, 'WM55D', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (2, 'AN95-4', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (6, 'BL05', '#00A03C');
INSERT INTO public.parkeerzones_map_color VALUES (50, 'BL01B', '#00A03C');
INSERT INTO public.parkeerzones_map_color VALUES (117, 'AN07', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (71, 'OZ31-03', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (17, 'OZ31-04', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (18, 'OZ30-06', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (19, 'OZ31-03', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (21, 'OZ31-03', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (83, 'OZ30-05', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (106, 'OZ31-03', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (13, 'WM54', '#00A03C');
INSERT INTO public.parkeerzones_map_color VALUES (75, 'BL01A', '#00A03C');
INSERT INTO public.parkeerzones_map_color VALUES (3, 'SV51', '#00A03C');
INSERT INTO public.parkeerzones_map_color VALUES (67, 'CE02', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (72, 'CE04', '#BED200');
INSERT INTO public.parkeerzones_map_color VALUES (55, 'WP61B', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (69, 'ZO01', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (54, 'WP61A', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (20, 'AN95-1', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (74, 'SO35A', '#767676');
INSERT INTO public.parkeerzones_map_color VALUES (33, 'WM58', '#00A03C');
INSERT INTO public.parkeerzones_map_color VALUES (24, 'SV50', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (1, 'BL04', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (103, 'OS76', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (53, 'WM56', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (73, 'GV81', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (87, 'BV85', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (88, 'BV85', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (104, 'BV85', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (102, 'OZ30-01', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (30, 'CE03', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (42, 'CE01', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (16, 'WH84A', '#BED200');
INSERT INTO public.parkeerzones_map_color VALUES (41, 'OS76', '#767676');
INSERT INTO public.parkeerzones_map_color VALUES (80, 'BA02', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (51, 'ZB69', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (52, 'ZB69', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (22, 'BV86', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (99, 'ZB08', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (82, 'AN06', '#E50082');
INSERT INTO public.parkeerzones_map_color VALUES (9, 'ZB09', '#009DEC');
INSERT INTO public.parkeerzones_map_color VALUES (12, 'WM57', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (68, 'ZB65', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (77, 'AN05C', '#BED200');
INSERT INTO public.parkeerzones_map_color VALUES (26, 'OW20', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (27, 'OW21', '#FF9100');
INSERT INTO public.parkeerzones_map_color VALUES (116, 'AN95-2', '#A00078');
INSERT INTO public.parkeerzones_map_color VALUES (25, 'ZB17', '#EC0000');
INSERT INTO public.parkeerzones_map_color VALUES (23, 'ZO02', '#009DEC');

--
-- PostgreSQL database dump complete
--

